name: Generate Podcast Feeds
on: [push]
jobs:
    job1:
        name: Update version
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Run Feed Generator
              uses: https://github.com/joshua-johnson-personal/podcast-generator.git@main
              

            
