name: Generate Podcast Feeds
on: [push]
jobs:
    job1:
        name: Update version
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Increase version
              run: |
               python -m pip install --upgrade pip
               pip install pyyaml
            - name: Run Feed Generator
              run: python feed.py
            - name: Push Repo
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "Modified Feed"
                  git push
            
