name: Generate Podcast Feeds
on: [push]
jobs:
    build:
        name: Update version
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Run Feed Generator
              uses: joshua-johnson-personal/podcast-generator@main
              

            
